//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DavcnaBlagajnaOdjemalec.Proxy
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://si.feri.soa/davcnablagajna/service/1.0", ConfigurationName="DavcnaBlagajnaOdjemalec.Proxy.DavcnaBlagajna")]
    public interface DavcnaBlagajna
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://si.feri.soa/davcnablagajna/service/1.0/DavcnaBlagajna/NovRacunRequest", ReplyAction="http://si.feri.soa/davcnablagajna/service/1.0/DavcnaBlagajna/NovRacunResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DavcnaBlagajnaOdjemalec.Proxy.NovRacunResponse> NovRacunAsync(DavcnaBlagajnaOdjemalec.Proxy.NovRacunRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://si.feri.soa/davcnablagajna/service/1.0/DavcnaBlagajna/novPoslovniProstorRe" +
            "quest", ReplyAction="http://si.feri.soa/davcnablagajna/service/1.0/DavcnaBlagajna/novPoslovniProstorRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DavcnaBlagajnaOdjemalec.Proxy.novPoslovniProstorResponse> novPoslovniProstorAsync(DavcnaBlagajnaOdjemalec.Proxy.novPoslovniProstorRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://si.feri.soa/davcnablagajna/data/racun/1.0")]
    public partial class Racun
    {
        
        private string datumField;
        
        private string davcnaStField;
        
        private string idField;
        
        private string ppIdField;
        
        private double znesekField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string datum
        {
            get
            {
                return this.datumField;
            }
            set
            {
                this.datumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string davcnaSt
        {
            get
            {
                return this.davcnaStField;
            }
            set
            {
                this.davcnaStField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ppId
        {
            get
            {
                return this.ppIdField;
            }
            set
            {
                this.ppIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double znesek
        {
            get
            {
                return this.znesekField;
            }
            set
            {
                this.znesekField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://si.feri.soa/davcnablagajna/data/poslovniprostor/1.0")]
    public partial class PoslovniProstor
    {
        
        private string davcnaStField;
        
        private string naslovField;
        
        private string ppIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string davcnaSt
        {
            get
            {
                return this.davcnaStField;
            }
            set
            {
                this.davcnaStField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string naslov
        {
            get
            {
                return this.naslovField;
            }
            set
            {
                this.naslovField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ppId
        {
            get
            {
                return this.ppIdField;
            }
            set
            {
                this.ppIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NovRacun", WrapperNamespace="http://si.feri.soa/davcnablagajna/service/1.0", IsWrapped=true)]
    public partial class NovRacunRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://si.feri.soa/davcnablagajna/service/1.0", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DavcnaBlagajnaOdjemalec.Proxy.Racun racun;
        
        public NovRacunRequest()
        {
        }
        
        public NovRacunRequest(DavcnaBlagajnaOdjemalec.Proxy.Racun racun)
        {
            this.racun = racun;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NovRacunResponse", WrapperNamespace="http://si.feri.soa/davcnablagajna/service/1.0", IsWrapped=true)]
    public partial class NovRacunResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://si.feri.soa/davcnablagajna/service/1.0", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DavcnaBlagajnaOdjemalec.Proxy.Racun @return;
        
        public NovRacunResponse()
        {
        }
        
        public NovRacunResponse(DavcnaBlagajnaOdjemalec.Proxy.Racun @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="novPoslovniProstor", WrapperNamespace="http://si.feri.soa/davcnablagajna/service/1.0", IsWrapped=true)]
    public partial class novPoslovniProstorRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://si.feri.soa/davcnablagajna/service/1.0", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DavcnaBlagajnaOdjemalec.Proxy.PoslovniProstor poslovniProstor;
        
        public novPoslovniProstorRequest()
        {
        }
        
        public novPoslovniProstorRequest(DavcnaBlagajnaOdjemalec.Proxy.PoslovniProstor poslovniProstor)
        {
            this.poslovniProstor = poslovniProstor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="novPoslovniProstorResponse", WrapperNamespace="http://si.feri.soa/davcnablagajna/service/1.0", IsWrapped=true)]
    public partial class novPoslovniProstorResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://si.feri.soa/davcnablagajna/service/1.0", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DavcnaBlagajnaOdjemalec.Proxy.PoslovniProstor @return;
        
        public novPoslovniProstorResponse()
        {
        }
        
        public novPoslovniProstorResponse(DavcnaBlagajnaOdjemalec.Proxy.PoslovniProstor @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface DavcnaBlagajnaChannel : DavcnaBlagajnaOdjemalec.Proxy.DavcnaBlagajna, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class DavcnaBlagajnaClient : System.ServiceModel.ClientBase<DavcnaBlagajnaOdjemalec.Proxy.DavcnaBlagajna>, DavcnaBlagajnaOdjemalec.Proxy.DavcnaBlagajna
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DavcnaBlagajnaClient() : 
                base(DavcnaBlagajnaClient.GetDefaultBinding(), DavcnaBlagajnaClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.DavcnaBlagajnaServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DavcnaBlagajnaClient(EndpointConfiguration endpointConfiguration) : 
                base(DavcnaBlagajnaClient.GetBindingForEndpoint(endpointConfiguration), DavcnaBlagajnaClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DavcnaBlagajnaClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DavcnaBlagajnaClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DavcnaBlagajnaClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DavcnaBlagajnaClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DavcnaBlagajnaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DavcnaBlagajnaOdjemalec.Proxy.NovRacunResponse> DavcnaBlagajnaOdjemalec.Proxy.DavcnaBlagajna.NovRacunAsync(DavcnaBlagajnaOdjemalec.Proxy.NovRacunRequest request)
        {
            return base.Channel.NovRacunAsync(request);
        }
        
        public System.Threading.Tasks.Task<DavcnaBlagajnaOdjemalec.Proxy.NovRacunResponse> NovRacunAsync(DavcnaBlagajnaOdjemalec.Proxy.Racun racun)
        {
            DavcnaBlagajnaOdjemalec.Proxy.NovRacunRequest inValue = new DavcnaBlagajnaOdjemalec.Proxy.NovRacunRequest();
            inValue.racun = racun;
            return ((DavcnaBlagajnaOdjemalec.Proxy.DavcnaBlagajna)(this)).NovRacunAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DavcnaBlagajnaOdjemalec.Proxy.novPoslovniProstorResponse> DavcnaBlagajnaOdjemalec.Proxy.DavcnaBlagajna.novPoslovniProstorAsync(DavcnaBlagajnaOdjemalec.Proxy.novPoslovniProstorRequest request)
        {
            return base.Channel.novPoslovniProstorAsync(request);
        }
        
        public System.Threading.Tasks.Task<DavcnaBlagajnaOdjemalec.Proxy.novPoslovniProstorResponse> novPoslovniProstorAsync(DavcnaBlagajnaOdjemalec.Proxy.PoslovniProstor poslovniProstor)
        {
            DavcnaBlagajnaOdjemalec.Proxy.novPoslovniProstorRequest inValue = new DavcnaBlagajnaOdjemalec.Proxy.novPoslovniProstorRequest();
            inValue.poslovniProstor = poslovniProstor;
            return ((DavcnaBlagajnaOdjemalec.Proxy.DavcnaBlagajna)(this)).novPoslovniProstorAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DavcnaBlagajnaServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DavcnaBlagajnaServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8081/davcnablagajna");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DavcnaBlagajnaClient.GetBindingForEndpoint(EndpointConfiguration.DavcnaBlagajnaServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DavcnaBlagajnaClient.GetEndpointAddress(EndpointConfiguration.DavcnaBlagajnaServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            DavcnaBlagajnaServicePort,
        }
    }
}
