GET http://localhost:8085/api/racuni

###
GET http://localhost:8085/api/racuni/136b54ca-238f-41ff-9464-c61ffcd914b5

###
POST http://localhost:8085/api/racuni
Content-Type: application/json

{
  "datum": "16.12.2025",
  "kraj": "Maribor",
  "znesek": 100,
  "ppId": "299292020202",
  "davcnaSt": "838484848"
}

###

PUT http://localhost:8085/api/racuni/7dbffca3-68f3-4bda-956f-4624211ad3ec
Content-Type: application/json

{
    "id": "7dbffca3-68f3-4bda-956f-4624211ad3ec",
    "datum": "16.12.2025",
    "kraj": "Maribor",
    "znesek": 400.0,
    "ppId": "299292020202",
    "davcnaSt": "838484848"
}

###
DELETE http://localhost:8085/api/racuni/7dbffca3-68f3-4bda-956f-4624211ad3ec
